gui:
  showNumstatInFilesView: true
git:
  branchLogCmd: "git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches"
  paging:
    colorArg: always
    pager: diff-so-fancy
    # pager: delta --dark --plus-style="#ffffff bold "#205115"" --plus-emph-style="#ffffff bold "#509940"" --minus-style="#ffffff bold "#701f1f"" --minus-emph-style="#ffffff bold "#e24646"" --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{f75445}:{line}"
    #8e2323
    #fc2a2a
