-- Base46 config (kept for fallback — uncomment to restore NvChad theme)
--
-- local M = {}
--
-- M.base46 = {
--   theme = "bearded-arc",
--   hl_override = {
--     DiagnosticUnderlineError = { sp = "red", undercurl = true },
--     DiagnosticUnderlineWarn = { sp = "yellow", undercurl = true },
--     DiagnosticUnderlineInfo = { sp = "blue", undercurl = true },
--     DiagnosticUnderlineHint = { sp = "purple", undercurl = true },
--   },
--   hl_add = {
--     DiagnosticUnderlineError = { sp = "red", undercurl = true },
--     DiagnosticUnderlineWarn = { sp = "yellow", undercurl = true },
--     DiagnosticUnderlineInfo = { sp = "blue", undercurl = true },
--     DiagnosticUnderlineHint = { sp = "purple", undercurl = true },
--   },
-- }
--
-- M.ui = {
--   tabufline = { enabled = false },
--   statusline = {
--     enabled = false,
--     theme = "default",
--     separator_style = "block",
--     lualine = true,
--   },
--   colorify = { enabled = false },
--   lsp = { signature = true },
-- }
--
-- return M

return {}
